baseURL = "https://juamiji1.github.io/My-webpage/"
languageCode = "en-us"
title = "Juan Miguel Jiménez"
theme = "academimal"
publishDir = "docs"
relativeURLs = false
canonifyURLs = true

[params]
  author = "Juan Miguel Jiménez"
  description = "PhD Candidate in Economics, UBC"
  bio = "PhD Candidate in Economics, UBC"

[params.social]
  github = "https://github.com/juamiji1"
  google_scholar = "https://scholar.google.com/citations?user=6k1wF6oAAAAJ&hl=es"


[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "CV"
    url = "files/"
    weight = 2

  [[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 3

